FROM node:20-bullseye

ENV NODE_PATH=/usr/local/lib/node_modules/

RUN npm install -g \
  "@code-pushup/coverage-plugin@^0.49.0" \
  "@code-pushup/js-packages-plugin@^0.49.0" \
  "@code-pushup/lighthouse-plugin@^0.49.0" \
  "@code-pushup/models@^0.49.0" \
  "@code-pushup/eslint-config@^0.8.0" \
  "@code-pushup/eslint-plugin@^0.50.0"
RUN npm install -g "@code-pushup/cli@^0.50.0"