build_docker_elixir:
  stage: build
  variables: 
    DOCKERFILE_PATH: $CI_PROJECT_DIR/docker/Dockerfile.elixir
    DESTINATION_IMAGE: $CI_REGISTRY_IMAGE/code-pushup-elixir:latest
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  when: manual
  script:
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --snapshot-mode=redo
      --use-new-run
      --dockerfile $DOCKERFILE_PATH
      --destination $DESTINATION_IMAGE