on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.20.4
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.4

    - name: Install dependencies
      run: |
        cd elixir
        npm ci

    - name: Build TypeScript
      run: |
        cd plugin
        npx tsc

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Build TypeScript [skip ci]" && git push)